---
# dependency:
#   name: galaxy
#   options:
#     role-file: requirements.yml
driver:
  name: docker
# lint:
#   name: yamllint
platforms:
  - name: instance
    image: "jrei/systemd-ubuntu:22.04"
    privileged: true
    command: "/lib/systemd/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - "SYS_ADMIN"
    tmpfs:
      - "/run"
      - "/run/lock"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../playbook.yml
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../../testinfra_all.py
